name: gocache
on:
  push:
    branches:
      - master

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Run orcas-doc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mskelton/setup-yarn@v1
      - name: Run build
        run: sh deploy.sh
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: docs/.vuepress/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
